---
version: "2"
services:
  openvpn-as:
    image: linuxserver/openvpn-as
    container_name: openvpn-as
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/London
    volumes:
      - ${CONFIG}:/config
    ports:
      - 943
      - 9443
      - 1194/udp
      - 1194/tcp
    restart: unless-stopped
