version: '3'
services:

  utorrent:
    container_name: "utorrent"
    image: dbarton/utorrent:latest
    restart: always
    dns: 8.8.8.8
    networks:
      - plex
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/config/plex-stack/utorrent:/config
      - /tmp:/tmp
      - /aws:/aws
    environment:
      - VIRTUAL_HOST=utorrent.vps.pknw1.co.uk
      - VIRTUAL_PORT=8080
      - PUID=666
      - PGID=666
    depends_on:
      - rclone-plex-config
      
  jackett:
    container_name: "jackett"
    image: linuxserver/jackett:latest
    restart: unless-stopped
    dns: 8.8.8.8
    networks:
      - plex
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/config/plex-stack/jackett:/config
      - /tmp:/tmp
    environment:
      - VIRTUAL_HOST=jackett.vps.pknw1.co.uk
      - VIRTUAL_PORT=9117
      - PUID=666
      - PGID=666
    depends_on:
      - rclone-plex-config
      
  cp:
    container_name: "cp"
    image: linuxserver/couchpotato:latest
    restart: unless-stopped
    dns: 8.8.8.8
    networks:
      - plex
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/config/plex-stack/cp:/config
      - /tmp:/tmp
      - /aws:/aws
    environment:
      - VIRTUAL_HOST=cp.vps.pknw1.co.uk
      - VIRTUAL_PORT=5050
      - PUID=666
      - PGID=666
    depends_on:
      - rclone-plex-config
      
  sickchill:
    container_name: "sickchill"
    image: linuxserver/sickchill:latest
    restart: unless-stopped
    dns: 8.8.8.8
    networks:
      - plex
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/config/plex-stack/sickchill:/config
      - /tmp:/tmp
    environment:
      - VIRTUAL_HOST=sickchill.vps.pknw1.co.uk
      - VIRTUAL_PORT=8081
      - PUID=666
      - PGID=666
    depends_on:
      - rclone-plex-config
      
  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin:latest
    restart: unless-stopped
    dns: 8.8.8.8
    networks:
      - plex
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/config/plex-stack/jellyfin/config:/config
      - /home/docker/config/plex-stack/jellyfin/cache:/cache
      - /tmp:/tmp
      - /aws:/aws
    environment:
      - VIRTUAL_HOST=jellyfin.vps.pknw1.co.uk
      - VIRTUAL_PORT=8096
      - PUID=666
      - PGID=666
    depends_on:
      - rclone-plex-config
      
networks:
  plex:
    driver: bridge
