version: '3'
services:
  rclone-plex:
    image: mumiehub/rclone-mount:latest
    container_name: rclone-plex
    restart: always
    networks:
      - plex
      - system
    volumes:
      - /etc/localtime:/etc/localtime
      - /tmp:/tmp
      - /root/.config/rclone:/config
      - /mnt/config:/mnt/plex_config:shared
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    environment:
      - TZ="Europe/London"
      - PUID="666"
      - PGID="666"
      - RemotePath=google-drive:/vps/plex_config
      - MountPoint=/mnt/plex_config
      - MountCommands=--uid 666 --gid 666 --umask 000 --allow-other --allow-non-empty
      
  utorrent:
    container_name: "utorrent"
    image: dbarton/utorrent:latest
    restart: always
    dns: 8.8.8.8
    networks:
      - plex
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/config/utorrent:/config
      - /tmp:/tmp
      - /aws:/aws
    environment:
      - VIRTUAL_HOST=utorrent.vps.pknw1.co.uk
      - VIRTUAL_PORT=8080
      - PUID=666
      - PGID=666
    depends_on:
      - rclone-plex
      
  jackett:
    container_name: "jackett"
    image: linuxserver/jackett:latest
    restart: unless-stopped
    dns: 8.8.8.8
    networks:
      - plex
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/config/jackett:/config
      - /tmp:/tmp
    environment:
      - VIRTUAL_HOST=jackett.vps.pknw1.co.uk
      - VIRTUAL_PORT=9117
      - PUID=666
      - PGID=666
    depends_on:
      - rclone-plex
      
  cp:
    container_name: "cp"
    image: linuxserver/couchpotato:latest
    restart: unless-stopped
    dns: 8.8.8.8
    networks:
      - plex
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/config/cp:/config
      - /tmp:/tmp
      - /aws:/aws
    environment:
      - VIRTUAL_HOST=cp.vps.pknw1.co.uk
      - VIRTUAL_PORT=5050
      - PUID=666
      - PGID=666
    depends_on:
      - rclone-plex
      
  sickchill:
    container_name: "sickchill"
    image: linuxserver/sickchill:latest
    restart: unless-stopped
    dns: 8.8.8.8
    networks:
      - plex
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/config/sickchill:/config
      - /tmp:/tmp
    environment:
      - VIRTUAL_HOST=sickchill.vps.pknw1.co.uk
      - VIRTUAL_PORT=8081
      - PUID=666
      - PGID=666
    depends_on:
      - rclone-plex
      
  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin:latest
    restart: unless-stopped
    dns: 8.8.8.8
    networks:
      - plex
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/config/jellyfin/config:/config
      - /mnt/config/jellyfin/cache:/cache
      - /tmp:/tmp
      - /aws:/aws
    environment:
      - VIRTUAL_HOST=jellyfin.vps.pknw1.co.uk
      - VIRTUAL_PORT=8096
      - PUID=666
      - PGID=666
    depends_on:
      - rclone-plex
      
networks:
  plex:
    driver: bridge
