version: '3'
services:

  docker-proxy:
    image: jwilder/nginx-proxy:latest
    container_name: docker-proxy
    networks:
      - plex
      - system
    volumes:
      -  /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/ssl:/etc/ssl
      - /etc/localtime:/etc/localtime
      - /tmp:/tmp
    environment:
      - TZ="Europe/London"
      - VIRTUAL_HOST="docker-proxy.pknw1.co.uk"	
      - VIRTUAL_PORT="80"
      - PUID="666"
      - PGID="666"
    ports:
      - 808:80
 
networks:
  system:
    driver: bridge
  plex:
    driver: bridge
