version: '2'
services:

  docker-proxy:
    image: jwilder/nginx-proxy:latest
    container_name: proxy
    networks:
      - plex
    volumes:
      -  /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - TZ="Europe/London"
    ports:
      - 80:80
 
networks:
  plex:
    driver: bridge
