version: '3'
services:

  docker-proxy:
    image: jwilder/nginx-proxy:latest
    container_name: docker-proxy
    networks:
      - plex
      - system
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/ssl:/etc/ssl
      - /etc/localtime:/etc/localtime
      - /tmp:/tmp
    environment:
      - TZ="Europe/London"
      - VIRTUAL_HOST="docker-proxy.pknw1.co.uk"
      - VIRTUAL_PORT="80"
      - PUID="666"
      - PGID="666"
    ports:
      - 808:80
      
 
  portainer:
    image: portainer/portainer:latest
    container_name: docker-portainer
    restart: always
    networks:
      - plex
      - system
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/ssl:/etc/ssl
      - /etc/localtime:/etc/localtime
      - /tmp:/tmp
      - ./config/portainer:/data
    environment:
      - TZ="Europe/London"
      - VIRTUAL_HOST="portainer.pknw1.co.uk"
      - VIRTUAL_PORT="9000"
      - PUID="666"
      - PGID="666"
    ports:
      - 9000:9000
    depends_on:
      - rclone-mount-config

  rclone-mount-config:
    image: mumiehub/rclone-mount:latest
    container_name: rclone-config
    restart: always
    networks:
      - plex
      - system
    volumes:
      - /etc/ssl:/etc/ssl
      - /etc/localtime:/etc/localtime
      - /tmp:/tmp
      - /root/.config/rclone:/config
      - /home/docker/config/plex-stack/:/mnt/config:shared
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    environment:
      - TZ="Europe/London"
      - PUID="666"
      - PGID="666"
      - RemotePath=google-drive:/vps
      - MountPoint=/mnt/config
      - MountCommands=--uid 666 --gid 666 --umask 000 --allow-other


  rclone-media:
    image: mumiehub/rclone-mount:latest
    container_name: rclone-media
    restart: always
    networks:
      - plex
      - system
    volumes:
      - /etc/ssl:/etc/ssl
      - /etc/localtime:/etc/localtime
      - /tmp:/tmp
      - /root/.config/rclone:/config
      - /aws/movies:/mnt/media/blob-pub/movies:shared
      - /aws/tv:/mnt/media/blob-pub/tv:shared
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    environment:
      - TZ="Europe/London"
      - PUID="666"
      - PGID="666"
      - RemotePath=ovh:/
      - MountPoint=/mnt/media
      - MountCommands=--uid 666 --gid 666 --umask 000 --allow-other

      
networks:
  system:
    driver: bridge
  plex:
    driver: bridge
    
