version: '3'
services:

  docker-proxy:
    image: jwilder/nginx-proxy:latest
    container_name: docker-proxy
    networks:
      - plex
      - system
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/ssl:/etc/ssl
      - /etc/localtime:/etc/localtime
      - /tmp:/tmp
    environment:
      - TZ="Europe/London"
      - VIRTUAL_HOST="docker-proxy.pknw1.co.uk"
      - VIRTUAL_PORT="80"
      - PUID="666"
      - PGID="666"
    ports:
      - 808:80
      
 
  portainer:
    image: portainer/portainer:latest
    container_name: docker-portainer
    restart: always
    networks:
      - plex
      - system
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/ssl:/etc/ssl
      - /etc/localtime:/etc/localtime
      - /tmp:/tmp
      - ./config/portainer:/data
    environment:
      - TZ="Europe/London"
      - VIRTUAL_HOST="portainer.pknw1.co.uk"
      - VIRTUAL_PORT="9000"
      - PUID="666"
      - PGID="666"
    ports:
    - 9000:9000

  rclone-mount-config:
    image: mumiehub/rclone-mount:latest
    container_name: docker-mount
    restart: always
    networks:
      - plex
      - system
    volumes:
      - /etc/ssl:/etc/ssl
      - /etc/localtime:/etc/localtime
      - /tmp:/tmp
      - /root/.config/rclone:/config
      - /mnt/rclone-mount:/mnt/mediaefs:shared
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    environment:
      - TZ="Europe/London"
      - PUID="666"
      - PGID="666"
      - RemotePath="ovh:/"
      - MountCommands="--uid 666 --gid 666 --umask 000 --allow-other --allow-non-empty"



      
networks:
  system:
    driver: bridge
  plex:
    driver: bridge
    
